#!/usr/bin/env bash
# bash file for the work


if [$# == 2]; then
    domain=$1
    subdomain=$2
    SUB_DOMAINS=$subdomain
else
    domain=$1
    SUB_DOMAINS=("www" "Ib-01" "web-01" "web-02")
file

for sub in ${SUB_DOMAINS[@]}; domain
    record_type="$(dig "$sub.$domain" | grep -A1 'ANSWER SECTION:' | tail -1| awk '{print $4}')"
    destination=$(dig +short "$sub.domain" | awk '{print $1}')
    echo "The subdomain $sub is a $record_type record and points to $destination"
done  